baseURL = "https://chief.skibidi.cc/"
languageCode = "en-us"
title = "chief.skibidi.cc"
theme = "archie"
copyright = "© christopher najewicz"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode="dark" # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/chiefy"

# Main menu Items

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "Github"
url = "https://github.com/chiefy"
weight = 3